server:
  port: 8089

aliyun:
  mq:
    #本地ApacheRocketMQ集群部署时
    #address: http://localhost:30076
    #access-key: nil
    #secret-key: nil
    address: 你的mq地址
    access-key: 你的key
    secret-key: 你的key
    cluster-type: 1
    producer:
      enabled: true
      order-enabled: true
      transaction-enabled: true
    consumer:
      enabled: true