server:
  port: 8089

aliyun:
  mq:
    address: http://localhost:30076
    access-key: nil
    secret-key: nil
    tag-suffix: -dev
    producer:
      enabled: true
      order-enabled: true
      transaction-enabled: true
    consumer:
      enabled: true